## TOML Uranio
db = "mongo"
encryption_rounds = 12
max_password_length = 58
storage = 'aws'
connect_on_init = false
superuser_create_on_init = true
prefix_api = '/uranio/api'
prefix_log = '/logs'
lambda = 'netlify'
fetch = 'axios'
[default_atoms]
	user = true
	media = true
[log]
	debug_info = true
	color = true
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[dev.log]
	debug_info = false
	color = true
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
